### PR TITLE
Debiasing Implementation

### PR DESCRIPTION
**Pull request by superp0tat0**

### CODE REVIEW

**Comment by mllg** [comment]
@superp0tat0 can you resolve the merge conflicts and give a quick update on the status? Is something missing or do you just wait for a review?

**Comment by superp0tat0** [comment]
> @superp0tat0 can you resolve the merge conflicts and give a quick update on the status? Is something missing or do you just wait for a review?

Hi, Michel

Right. I was thinking about finishing the equalized odds debiasing in this branch then resolve the conflicts. I do not have much time for this month but I guess I could get it done by the start of October.

**Comment by pfistfl** [comment]
@superp0tat0 
We are currently doing a small sprint. I could either take this over or you try to make progress until 1st of October ?

**Comment by superp0tat0** [comment]
> @superp0tat0 We are currently doing a small sprint. I could either take this over or you try to make progress until 1st of October ?

Hi, Florian. The problem is I am currently working full time and got interviews tomorrow, Oct 2nd, Oct 5th, and Oct 6th. I could use Oct 7th and Oct 8th to finish this task. If you think that is somehow late then you could definitely take over that. Sorry for not being able to deliver that task, just the interview season is mainly end of November and start of October. I should be more available later.

**Comment by superp0tat0** [comment]
The merge conflicts have been fixed and the branch should be good to go.

**Pull request merged**
